#! /bin/sh

bspc config border_width        2
bspc config window_gap         12
bspc config top_padding		15

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config focused_border_color "#268bd2"
bspc config normal_border_color "#373b41"
bspc config presel_border_color "#e5e5e5"

bspc monitor -d term web code misc


bspc rule -a Gimp desktop=misc follow=on floating=on
bspc rule -a Chromium desktop=web
bspc rule -a mplayer2 floating=on

xsetroot -cursor_name left_ptr &

panel &
